version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: cicd-fitness-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - fitness-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example  # Change this in production!
  
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cicd-fitness-backend
    restart: always
    depends_on:
      - mongodb
    networks:
      - fitness-network
    ports:
      - "4001:4001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4001
      - NODE_ENV=production
    env_file:
      - ./server/.env

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cicd-fitness-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - fitness-network
    ports:
      - "82:80"  # Changed to port 82 as requested
    volumes:
      - ./client:/app/code

networks:
  fitness-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 